MDScreen:
    MDCard:
        size_hint: None, None
        size: dp(100), dp(100)
        md_bg_color: "#000000"
        radius: [dp(100), ]
        pos_hint: {"center_x": .11, 'center_y': .5}
    FitImage:
        id: avatar
        size_hint: None, None
        size: dp(95), dp(95)
        md_bg_color: "#000000"
        radius: [dp(95), ]
        pos_hint: {"center_x": .11, 'center_y': .5}
        source: app.avatar_source